newer releaser and docker-ops; do not use oversion

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -1,72 +1,75 @@
 #!/bin/bash
 
-set -e
-if [[ ! -f ./releaser ]];then
-  wget --quiet http://http.archive.ai-traders.com/releaser/1.0.6/releaser
+set -Eeuo pipefail
+if [[ ! -f ./releaser ]]; then
+  wget --quiet http://http.archive.ai-traders.com/releaser/1.1.0/releaser || { echo "Cannot download releaser, ignoring."; }
 fi
-source ./releaser
+if [[ -f ./releaser ]]; then
+  source ./releaser
+fi
 if [[ ! -f ./docker-ops ]];then
-  wget --quiet http://http.archive.ai-traders.com/docker-ops/0.2.2/docker-ops
+  wget --quiet http://http.archive.ai-traders.com/docker-ops/0.3.3/docker-ops || { echo "Cannot download docker-ops, ignoring."; }
 fi
-source ./docker-ops
-# This goes as last in order to let end user variables override default values
-releaser_init
+if [[ -f ./docker-ops ]];then
+  source ./docker-ops
+fi
 
-image_name="docker-registry.ai-traders.com/terraformide"
+image_name="terraformide"
+image_registry="docker-registry.ai-traders.com"
 image_dir="./image"
 imagerc_filename="imagerc"
 
 command="$1"
+set +u
 case "${command}" in
   set_version)
       if [[ -n "$2" ]]; then
         next_version="$2"
-        set_version_in_changelog "${changelog_file}" "${next_version}"
-        set_next_oversion "${next_version}"
       else
-        next_version=$(get_next_oversion)
-        set_version_in_changelog "${changelog_file}" "${next_version}"
+        version=$(releaser::get_last_version_from_whole_changelog "${changelog_file}")
+        next_version=$(releaser::bump_patch_version "${version}")
       fi
+      releaser::set_version_in_changelog "${changelog_file}" "${next_version}"
       exit $?
       ;;
   verify_version)
-      verify_version_for_release
+      releaser::verify_changelog_version
       exit $?
       ;;
   build)
-      docker_build "${image_dir}" "${imagerc_filename}" "${image_name}" "$2"
+      image_tag=$(git rev-parse HEAD)
+      ( set -x; cd "${image_dir}"; docker build -t "${image_name}:${image_tag}" .; )
+      docker_ops::create_imagerc "${image_dir}" "${imagerc_filename}" "${image_name}" "${image_tag}" "${image_registry}"
+      docker_ops::push_tmp "${image_name}" "${image_tag}" "${image_registry}"
       exit $?
       ;;
   itest)
-      source_imagerc "${image_dir}"  "${imagerc_filename}"
-      echo "Testing image: ${AIT_DOCKER_IMAGE_NAME}:${AIT_DOCKER_IMAGE_TAG}"
-      echo "DOJO_DOCKER_IMAGE=\"${AIT_DOCKER_IMAGE_NAME}:${AIT_DOCKER_IMAGE_TAG}\"" > ./Dojofile.to_be_tested
+      docker_ops::ensure_temp_image "${image_dir}" "${imagerc_filename}"
+      echo "Testing image: ${AIT_DOCKER_IMAGE_URL}"
+      echo "DOJO_DOCKER_IMAGE=\"${AIT_DOCKER_IMAGE_URL}\"" > ./Dojofile.to_be_tested
       echo "DOJO_IDENTITY_OUTER=\"$(pwd)/test/integration/identities/full\"" >> ./Dojofile.to_be_tested
       echo "DOJO_WORK_OUTER=$(pwd)/test/integration/test_dojo_work" >> ./Dojofile.to_be_tested
       time bats "$(pwd)/test/integration/end_user"
       exit $?
       ;;
   example)
-      source_imagerc "${image_dir}"  "${imagerc_filename}"
-      echo "Testing image: ${AIT_DOCKER_IMAGE_NAME}:${AIT_DOCKER_IMAGE_TAG}"
-      echo "DOJO_DOCKER_IMAGE=\"${AIT_DOCKER_IMAGE_NAME}:${AIT_DOCKER_IMAGE_TAG}\"" > ./Dojofile.example
+      docker_ops::ensure_temp_image "${image_dir}" "${imagerc_filename}"
+      echo "Testing image: ${AIT_DOCKER_IMAGE_URL}"
+      echo "DOJO_DOCKER_IMAGE=\"${AIT_DOCKER_IMAGE_URL}\"" > ./Dojofile.example
       echo "DOJO_IDENTITY_OUTER=\"$(pwd)/test/integration/identities/full\"" >> ./Dojofile.example
       echo "DOJO_WORK_OUTER=$(pwd)/test/integration/test_dojo_work" >> ./Dojofile.example
       dojo -c ./Dojofile.example
       ;;
   release)
-      verify_version_for_release
-      git_tag_from_oversion
-      old_version=$(get_next_oversion)
-      next_version=$(bump_patch_version "${old_version}")
-      set_next_oversion "${next_version}"
+      ./tasks verify_version
+      version=$(releaser::get_last_version_from_whole_changelog "${changelog_file}")
+      git tag "${version}" && git push origin "${version}"
       exit $?
       ;;
   publish)
-      production_image_tag=$(get_last_version_from_changelog "${changelog_file}")
-      validate_version_is_semver "${production_image_tag}"
-      source_imagerc "${image_dir}"  "${imagerc_filename}"
-      docker_push "${AIT_DOCKER_IMAGE_NAME}" "${AIT_DOCKER_IMAGE_TAG}" "${production_image_tag}"
+      version=$(releaser::get_last_version_from_whole_changelog "${changelog_file}")
+      validate_version_is_semver "${version}"
+      docker_ops::push_production "${image_dir}"  "${imagerc_filename}" "${image_name}" "${version}" "${image_registry}"
       exit $?
       ;;
   *)
